### ISSUE TITLE
get list of categories limit issue

### ISSUE THREAD

**Issue by KalpeshjagannathMahajan** [Bixoto/PyMagento#3]
the function "get_categories" does not accepts limit parameter and hence can not send it to "get_paginated" function and the api fails with error "magento.exceptions.MagentoException: Maximum SearchCriteria pageSize is 300"

**Comment by bfontaine** [comment]
Hello and thank you for the report, I fixed it and will release 1.7.3 shortly.

**Comment by bfontaine** [comment]
Done: https://pypi.org/project/pymagento/1.7.3/

**Comment by KalpeshjagannathMahajan** [comment]
thanks a lot
